<?php
/**
 * Created by PhpStorm.
 * User: yf
 * Date: 2018/3/10
 * Time: 下午5:56
 */

namespace App\Utility;


use EasySwoole\Config;
use EasySwoole\Core\AbstractInterface\AbstractCoroutinePool;
use EasySwoole\Core\AbstractInterface\Singleton;
use EasySwoole\Core\Component\Logger;
use EasySwoole\Core\Swoole\Coroutine\Client\Mysql;


class MysqlPool2 extends AbstractCoroutinePool
{

    function __construct(int $min = 3, int $max = 20)
    {
        $max = 5;
        $min = 2;

        parent::__construct($min, $max);
    }

    function getObj():?Mysql
    {
        return parent::getObj(); // TODO: Change the autogenerated stub
    }

    protected function createObject()
    {
        // TODO: Implement createObject() method.
        $conf = Config::getInstance()->getConf('MYSQL');
        $db = new Mysql([
            'host' => $conf['HOST'],
            'port' => 3306,
            'username' => $conf['USER'],
            'password' => $conf['PASSWORD'],
            'db' => $conf['DB_NAME']
        ]);
        return $db;
    }
}