<?php
/**
 * Created by PhpStorm.
 * User: yf
 * Date: 2018/3/8
 * Time: 下午4:53
 */

namespace App\Utility;


use EasySwoole\Config;
use EasySwoole\Core\AbstractInterface\AbstractCoroutinePool;
use \Swoole\Coroutine\MySQL;

class MysqlPool extends AbstractCoroutinePool
{

    function getObj():?MySQL
    {
        return parent::getObj(); // TODO: Change the autogenerated stub
    }

    function __construct()
    {
        //每个进程最多5个连接
        $this->maxNum = 5;
        parent::__construct();
    }

    protected function createObject()
    {
        // TODO: Implement createObject() method.
        $conf = Config::getInstance()->getConf('MYSQL');
        $swoole_mysql = new MySQL();
        $swoole_mysql->connect([
            'host' => $conf['HOST'],
            'port' => 3306,
            'user' => $conf['USER'],
            'password' => $conf['PASSWORD'],
            'database' => $conf['DB_NAME']
        ]);
        return $swoole_mysql;
    }
}