<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 18-11-1
 * Time: 上午11:55
 */

namespace App\HttpController;


use App\Utility\Pool\MysqlObject;
use App\Utility\Pool\MysqlPool;
use EasySwoole\Component\Pool\PoolManager;
use EasySwoole\EasySwoole\Config;

abstract class BaseWithDb extends Base
{
    protected $db;

    function onRequest(?string $action): ?bool
    {
        $db = PoolManager::getInstance()->getPool(MysqlPool::class)->getObj(Config::getInstance()->getConf('MYSQL.POOL_TIME_OUT'));
        if ($db) {
            $this->db = $db;
        } else {
            //直接抛给异常处理，不往下
            throw new \Exception('url :'.$this->request()->getUri()->getPath().' error,Mysql Pool is Empty');
        }
        return parent::onRequest($action); // TODO: Change the autogenerated stub
    }

    protected function gc() {
        PoolManager::getInstance()->getPool(MysqlPool::class)->recycleObj($this->db);
        parent::gc();
    }

    protected function getDbConnection(): MysqlObject {
        return $this->db;
    }

}