<?php
/**
 * Created by PhpStorm.
 * User: yf
 * Date: 2018/8/15
 * Time: 上午12:01
 */

namespace App\HttpController;


use App\Utility\TrackerManager;
use EasySwoole\Http\AbstractInterface\Controller;
use EasySwoole\Trace\Bean\TrackerPoint;

class Trace extends Controller
{
    function onRequest(?string $action): ?bool
    {
        $tracker = TrackerManager::getInstance()->getTracker('new tracker');

        return parent::onRequest($action); // TODO: Change the autogenerated stub
    }

    function index()
    {
        $tracker = TrackerManager::getInstance()->getTracker();

        $tracker->addAttribute('user', '用户名1');
        $tracker->addAttribute('name', '这是昵称');
        $trackerPoint = $tracker->setPoint('查询用户订单', [
            'sql' => 'sql statement one'
        ]);
        //模拟sql 执行
        usleep(1000000);
        $tracker->endPoint('查询用户订单', $trackerPoint::STATUS_FAIL, ["查询失败"]);

        $this->response()->write('call trace');

    }

    function newTracker()
    {
        $tracker = TrackerManager::getInstance()->getTracker('new tracker');

        $tracker->addAttribute('user', '仙士可');
        $trackerPoint = $tracker->setPoint('测试运行时间', [
            'param' => '巴拉巴拉'
        ]);
        sleep(1);
        $trackerPoint->endPoint(TrackerPoint::STATUS_SUCCESS);
        $this->response()->write("new tracker is run.\n");
        var_dump($tracker->toString());
    }

    function afterAction(?string $actionName): void
    {
        $tracker = TrackerManager::getInstance()->closeTracker('new tracker');
        parent::afterAction($actionName); // TODO: Change the autogenerated stub
    }
}